name: Signaler un bug
about: Signaler des bugs nous permet d'améliorer LGDC Forum
title: "[BUG]: "
labels: bug
type: Bug

body:
  - type: textarea
    attributes:
      label: Description du bug
      description: Plus il y a de détails, plus vite nous pourrons trouver le bug !
      placeholder: Je ne peux pas envoyer de messages depuis le module python.
    validations:
      required: true


  - type: textarea
    attributes:
      label: Qu'attendez-vous de nous ?
      description: Que peux-t-on faire pour vous aider ?
      placeholder: Que je puisse envoyer des messages depuis le module python.
    validations:
      required: true


  - type: input
    attributes:
      label: Appareil
      description: Sur quel appareil avez-vous rencontré ce bug ?
      placeholder: iPhone12, Galaxy S23...
    validations:
      required: true

  - type: input
    attributes:
      label: Version de l'OS
      description: Paramètres (du Téléphone) -> À propos (Android)/Général (Apple)
      placeholder: iOS 26, Android 15...
    validations:
      required: true

  - type: dropdown
    attributes:
      label: Vous utilisez
      description: Vous avez utilisé LGDC Forum depuis...
      options:
        - Site
        - PWA
        - Module python
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Capture(s) d'écran"
      description: Cela permettra une résolution encore plus rapide du bug
      placeholder: Des captures d'écran peuvent nous aider à comprendre le problème (utilisez le 📎 plus bas)
    validations:
      required: false
